### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by saurabhkankriya** [koaning/calmcode-feedback#1]
I really love the short and concise tutorials that you have put up. The tutorials are brilliant. Just enough information to get started with the tool and then it is upto us on how to use it further. Thank you so much. 

I have been following  you on twitter. Also, thismonth.rocks is another great project that has helped me come up with my own list of small projects that I can do on my own. 

Thanks. Please keep making the tutorials. :)

**Comment by koaning** [comment]
Kind words. Thanks. 

Not really an issue though :) so I think I can close this one.

**Comment by koaning** [comment]
Also ... if you've got cool stuff. You can add it to thismonth.rocks too right?

**Comment by saurabhkankriya** [comment]
I would love to! Any guidelines? I have never contributed to any other repo before this

**Comment by koaning** [comment]
https://thismonth.rocks/ lists a tutorial on top. It's a video explaining all the steps from within the browser.
