### ISSUE TITLE
Missing `grid` import

### ISSUE THREAD

**Issue by david26694** [koaning/calmcode-feedback#102]
Hi, thanks again for very interesting resources. The `grid` function doesn't seem to be imported [here](https://calmcode.io/memo/grid.html):
![image](https://user-images.githubusercontent.com/22721584/120890041-a9713380-c600-11eb-91ae-b28945d79ef4.png)

Thanks!

**Comment by david26694** [comment]
Same issue in https://calmcode.io/memo/runner.html

**Comment by koaning** [comment]
Made the changes ready for the next PR. 

Thanks for reporting!
