### ISSUE TITLE
Change "emphesis" to "emphasis"

### ISSUE THREAD

**Issue by stevebang** [koaning/calmcode-feedback#103]
I think you meant "emphasis"...

https://calmcode.io/rich/introduction.html

Looks like the file name has the error too.

https://calmcode.io/rich/emphesis.html

**Comment by stevebang** [comment]
https://en.wikipedia.org/wiki/Emphasis_(typography)

**Comment by koaning** [comment]
Well spotted! Thanks :) 

Added!
