### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by thepooons** [koaning/calmcode-feedback#104]
Don't forget to add a link (or a screenshot) of what needs a-fixin.
![Screenshot (147)](https://user-images.githubusercontent.com/66294486/122726293-7fbc3b80-d293-11eb-8a33-4d27196bdddb.png)
Found a typo in the **Notes** section [here](https://calmcode.io/remote/planning.html).
Perhaps you mistyped "things" as "thigns".

PS: Loving this project!

**Comment by koaning** [comment]
Thanks! 

These edits have just been comitted. PR should be live in a few minutes.
