### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by daltonturner** [koaning/calmcode-feedback#105]
Could be wrong here, but I had to prepend `data` with `employee_salaries.` on line 2 in the [introduction's](https://calmcode.io/dirty-cat/introduction.html) code to get this to run properly. Love calmcode! 

![Screen Shot 2021-06-30 at 8 10 08 PM](https://user-images.githubusercontent.com/28828377/124059100-63c94000-d9df-11eb-9498-4cd2b38bd1d7.png)

**Comment by koaning** [comment]
Ah correct! 

It needs to be;

```python
import numpy as np
import pandas as pd
from dirty_cat import datasets

employee_salaries = datasets.fetch_employee_salaries()
data = employee_salaries['data']
```

followed by 

```python
target_column = 'Current Annual Salary'
ml_df = data[[target_column, 'year_first_hired', 'assignment_category', 'employee_position_title']].dropna()
y = ml_df[target_column].values.ravel()
X = ml_df[['employee_position_title', 'year_first_hired', 'assignment_category']]
```

Will take care of it during the next PR! Thanks for reporting :)

**Comment by daltonturner** [comment]
Awesome! I don't know if you'd like a separate issue to be submitted, but I noticed the `.vocabulary_` attribute was also abbreviated to `.vocab_` in the code snippets for the following videos as well.

**Comment by koaning** [comment]
These edits have just been comitted. PR should be live in a few minutes.
