### ISSUE TITLE
Patsy incremental learning and mlflow for logging (just the tips)

### ISSUE THREAD

**Issue by petrhrobar** [koaning/calmcode-feedback#106]
Hey There, Vincent,

I love the content you are making and I also love patsy as a library.
I recently came accros an issue with patsy - it is slow with larger dataset.

However, we can use incremental creation of the design matrix. I was thinking would you consider adding this feature to the concent?

Secondly, I like your memo library for logging but the mlflow is also an amazing framework. Have you played around with mlflow yet? Would you consider adding mlflow to a very long lists of topics to cover?

Best,

Petr

**Comment by koaning** [comment]
I'm not sure I'm familiar with the "incremental creation" feature you mention for patsy, got a link?

I gotta admit, `mlflow` isn't *that* high on the priority list. I've seen some demos of it and while I agree there's stuff to like. It feels like there's more pressing content that deserves some more attention.

**Comment by petrhrobar** [comment]
Patsy incremental creating is referred as *patsy.incr_dbuildersk*, it is documented e.g. [here](https://patsy.readthedocs.io/en/v0.2.0/API-reference.html).

However, the documentation is a bit uninformative but luckily someone had already asked at stackoverflow [here](https://stackoverflow.com/questions/26501609/how-to-prepare-large-datasets-with-patsys-api)

also, agreed about other pressing content

**Comment by koaning** [comment]
I fear however that the chunking approach only works within chunks. 

Say I want to one-hot encode animal types, like [cat, dog, mouse]. 

If the first batch only contains `[cat, dog]` examples, and the second batch only contains `[dog, mouse]` examples ... how would you encode appropriately? A one-hot encoder on the entire dataset would add 3 columns while patsy would only add 2 for each batch.

**Comment by petrhrobar** [comment]
Hi VIncent, 
good point indeed. 
What I would do is to make sure that each chunk contains every unique level of variables to be dummy coded. Therefore, I would not create chunks chronologically (by rows of data frame) but randomly.

BTW, how do you use patsy in production when working with larger datasets? Does AWS handle it?

**Comment by koaning** [comment]
I've always been able to get away with models that are just ... light and understandable. When-ever datasets got bigger I've always been able to manage by either 1.) just waiting a bit longer or 2.) getting a larger machine/container on AWS. 

I've made a tool called [tokenwiser](https://koaning.github.io/tokenwiser/) for text models though. One of the core features of that library is that it's able to handle everything in a streaming setting. 

This is a nice reminder, I need to add content on `partial_fit` on calmcode. More info on that scikit-learn trick [here](https://koaning.io/posts/passive-agressive-algorithms/).

**Comment by koaning** [comment]
As a general pro-tip though: consider a simple light-weight model first as a benchmark. Data quality is more important than a heavy ML pipeline.

**Comment by koaning** [comment]
Closing the issue due to inactivity.
