### ISSUE TITLE
Likely miss in code sample at https://calmcode.io/decorators/inputs.html

### ISSUE THREAD

**Issue by RonakAgrawal77** [koaning/calmcode-feedback#111]
We are overwriting the output of the function `result` w/ the `log_text`
![image](https://user-images.githubusercontent.com/58680482/126592963-10dab3f2-ecec-4271-a0f2-fa81de670ff0.png)

Apologies if I missed something obvious.

**Comment by koaning** [comment]
For the future, if you post the link inline [like so](https://calmcode.io/decorators/inputs.html) you'll get a link that's easy to click. Will look into it!

**Comment by koaning** [comment]
But yeah, it looks like you're right. Will pick this up for the PR this weekend. Thanks for reporting!

**Comment by koaning** [comment]
Fixed in next PR.
