### ISSUE TITLE
Wrong screen recording on jq page

### ISSUE THREAD

**Issue by kayhoogland** [koaning/calmcode-feedback#112]
On the [page for jq](https://calmcode.io/shorts/jq.html) it shows the video for grep. 

![image](https://user-images.githubusercontent.com/22837350/128349551-2479eaf8-cb6e-46b3-8ddc-052e73f3b1cb.png)

**Comment by koaning** [comment]
"le oops" 

on it.

**Comment by koaning** [comment]
PR is being merged now. Thanks for reporting!
