### ISSUE TITLE
Video tutorial about creating a "calmcode article"

### ISSUE THREAD

**Issue by koenvo** [koaning/calmcode-feedback#12]
The articles on calmcode.io are really awesome. It would be great to have a tutorial on how to create such a article with videos. Let's call it the "Making of" :-)

Possible steps:
1. How to come up with a idea for an article
2. How to determine the steps
3. What needs to be explained in each step
4. What are good examples to use in the example
5. etc etc

So in the end also other people can contribute to calmcode.

**Comment by koaning** [comment]
I figured I'd post something here in the meantime. At the moment, quite honestly, I haven't really got my process set in stone. I've started looking back at older videos and it got me wondering why I made certain decisions. I'll happily add content for this, but I just want to formalise my creation process a bit more before I make content for it. I'd hate to have to redo it.

**Comment by koaning** [comment]
It sure took me a while, and it's not everything, but it's a start. 

https://calmcode.io/content/introduction.html

**Comment by koenvo** [comment]
Whoop whoop 🙌
