### ISSUE TITLE
Accessing readme.so link shows 404 error

### ISSUE THREAD

**Issue by yudhiesh** [koaning/calmcode-feedback#122]
In the page [readme-files](http://mail01.tinyletterapp.com/calmcode/calmcode-more-rich-readme-and-ssh/19846570-calmcode.io/readme-files/readme.so.html?c=ba718027-06af-650b-b201-6c070b730cc6), when I click on the link to [readme.so](https://readme.so/) it shows a 404 error as linked in the screenshot below:

![Screenshot 2021-08-23 at 9 40 48 AM](https://user-images.githubusercontent.com/55042754/130378708-56663894-d81b-4f99-bccb-6e120fab37b1.png)

**Comment by koaning** [comment]
Ah! Yeah, you're not the only one who noticed that. I've put it on the PR 

Thanks for letting me know!
