### ISSUE TITLE
In logging vidoes: CRITICAL should be above ERROR

### ISSUE THREAD

**Issue by Stannislav** [koaning/calmcode-feedback#138]
In the video and the code example on https://calmcode.io/logging/level.html the order of the logging levels is wrong

it should be
```python
logger.debug('this is a debug statement')
logger.info('this is a info statement')
logger.warning('this is a warning statement')
logger.error('this is a error statement')
logger.critical('this is a critical statement')
```
I swapped the last two lines: CRITICAL is more critical than ERROR. Source: https://docs.python.org/3/library/logging.html#logging-levels

**Comment by koaning** [comment]
Well spotted! It's on the todo.

**Comment by koaning** [comment]
Done.
