### ISSUE TITLE
Seems like most links are overwriting current tab content

### ISSUE THREAD

**Issue by mco-gh** [koaning/calmcode-feedback#139]
Perhaps this is by design but I find that I'm often reading some of your text, or partway through a mini-course, when you share a link to a related resource. I think, "hmm...let's see what's there and maybe save it for future reference" but then poof - there goes my current thread.

Using "target="_blank" on the <a> elements would ensure your links open in a new tab. If you agree, I'd be happy to submit a PR.

**Comment by koaning** [comment]
That's valid. URLs in the appendix often aren't related to site navigation so those may be better to open in a new tab.

I'll need to investigate if this holds true in general, but if so I should be able to update the jinja templates.

**Comment by koaning** [comment]
At the moment, I don't host the tutorials out in the open. Your PR attitude is certainly appreciated though. 🙂

**Comment by koaning** [comment]
The new site should fix this. Might come live tonight!
