### ISSUE TITLE
Typo "import this" instead of "import time"

### ISSUE THREAD

**Issue by njanakiev** [koaning/calmcode-feedback#142]
Thanks for the great tutorial series, very well structured!

The error was found here:

- https://calmcode.io/tqdm/descriptions.html
- https://calmcode.io/tqdm/nested-loops.html

**Comment by koaning** [comment]
Well spotted. 

In general though, I do advice anyone to run `import this` at least once in their Python career. 

You may even find that popular packages implement this! Protip: 

```python
from sympy import this
from sklego import this
```

**Comment by koaning** [comment]
Fixed in the next PR. Thanks for reporting!

**Comment by njanakiev** [comment]
Haha, very nice Easter egg indeed!
