### ISSUE TITLE
Loved the noisy label learning one :) 

### ISSUE THREAD

**Issue by duarteocarmo** [koaning/calmcode-feedback#146]
Don't forget to add a link (or a screenshot) of what needs a-fixin.

**Comment by koaning** [comment]
Happy to hear it. But ... what content are you referring to 😅 ?

**Comment by duarteocarmo** [comment]
It’s in the issue title! [The noisy label learning](https://calmcode.io/bad-labels/noisy-label-learning.html) one

**Comment by koaning** [comment]
Ahhh that one. 

Yeah, so there's 600+ videos now on the platform. So even for me it's gotten to the point where I don't remember all of them. 😅 

One thing about noisy label learning, while it's a cool trick ... it's better to also invest in cleaning up labels than to put all hope into a model that might be able to deal with some bad ones.
