### ISSUE TITLE
On ubuntu and debian the command for yank is yank-cli

### ISSUE THREAD

**Issue by rluthi** [koaning/calmcode-feedback#147]
More info: [yank GitHub](https://github.com/mptre/yank#debian)

![image](https://user-images.githubusercontent.com/18192364/149471286-ffbd7f8e-8132-469f-84f4-a56fb7829d99.png)

**Comment by rluthi** [comment]
Additionally, on Windows 10 and WSL I have to explicitly send the output to the clipboard :  `ls -lhat | yank | clip.exe` 

For the simple use-case of copying terminal outputs, I was able to make it work with `alias yank="yank-cli | clip.exe"`

**Comment by koaning** [comment]
That's odd. Added it on the todo list to explore further though. Thanks for reporting :)

**Comment by koaning** [comment]
Didn't have the opportunity to properly explore it, but I have made a PR that adds this info to the `yank` content.
