### ISSUE TITLE
Calm Coffee needs a bump in Stripe

### ISSUE THREAD

**Issue by ceteri** [koaning/calmcode-feedback#148]
When someone tries to send a _Calm Coffee_, just after providing the payment details there's an error:
> Invalid Stripe API version:

Would be good to buy you more coffees!

**Comment by koaning** [comment]
That's ... strange. This is after the experience in the ko-fi platform?

**Comment by koaning** [comment]
I've submitted a ticket just in case.

**Comment by koaning** [comment]
This is their response, supposedly everything should be fixed now. 

![image](https://user-images.githubusercontent.com/1019791/151695925-33296d01-5d7e-4262-a515-84ca0b826b68.png)

**Comment by ceteri** [comment]
Great, glad that helped!
