### ISSUE TITLE
Streamlit 

### ISSUE THREAD

**Issue by RaminParker** [koaning/calmcode-feedback#151]
In the docu you write: 
````values = np.cumsum(1 + np.random.normal(x, y, (100, 10)), axis=0)````

But I think you mean:
````values = np.cumprod(1 + np.random.normal(x, y, (100, 10)), axis=0)````

See link: https://calmcode.io/streamlit/line-charts.html

**Comment by koaning** [comment]
Well spotted. Just pushed a PR for a quick fix. Thanks 👍
