### ISSUE TITLE
404

### ISSUE THREAD

**Issue by njr0** [koaning/calmcode-feedback#155]
Hey Vincent!

Not sure you'll actually want this, but I was just looking to tweet a link to your stuff on rich. I went to

https://calmcode.io/rich/introduction.html

and thought "that's an ugly URL to post for the whole of rich", so tried going to 

https://calmcode.io/rich

(or maybe https://calmcode.io/rich/ ? Those can, as you know, be more different that I think they ought to be).

And I got a 404 that said 

404
oops ... that shouldn't happen
Could you please let us know how you got here? We'll put a fix on our todo!

And I'm only reporting because...well, a person could read that as a request to report stuff like this!

Now, I suspect the devil on your right shoulder is going to say "Yes, but I didn't mean type any old shit into the URL bar and report it if it doesn't work".

But I also suspect the restful angel on your left shoulder is going to say "URLs should be beautiful and are part of the interface, and https://calmcode.io/rich (or https://calmcode.io/rich/) is a much nicer, more guessable place for people to go on Calc Code to find out about rich. So maybe this completely unreasonable problem report isn't *totally* unreasonable."

Anyway, your call. Great site. Good videos on rich. Shame about the URL.

... and YOU DID ASK!

**Comment by njr0** [comment]
Oh, and there's this:
![Screenshot 2022-03-16 at 08 31 23](https://user-images.githubusercontent.com/117818/158548858-02d346f9-c0ef-472b-b948-089df54e5a52.png)

How much better would that have looked with a restful URL?

**Comment by koaning** [comment]
Yeah, this was totally a fair criticism and a design mistake on my part back in the day. It's on my todo-list to implement redirects such that `calmcode.io/rich` just forwards to `calmcode.io/rich/introduction.html`.

**Comment by koaning** [comment]
I wonder ... doesn't Twitter usually turn the URL into their own shortned standard?

**Comment by koaning** [comment]
The new site will totally fix this. Maybe even tonight!
