### ISSUE TITLE
Typo: extra ) in pandas datetime: resample

### ISSUE THREAD

**Issue by alina-artcibasova** [koaning/calmcode-feedback#156]
A small typo in [pandas datetime: resample](https://calmcode.io/pandas-datetime/resample.html) in "Together with Groupby" code box, should be:

```{python}
(df[['state', 'date', 'births']]
      .assign(date=lambda d: pd.to_datetime(d['date'], format="%Y-%m-%d"))
      .set_index('date')
      .groupby('state')
      .resample('2W').sum())
```

**Comment by koaning** [comment]
Could you add a link to the course? Given that there are 600+ these days ... it's a bit tricky for me to remember which code snippet is part of which lesson.

**Comment by alina-artcibasova** [comment]
Sure thing, updated the main post now.

**Comment by koaning** [comment]
Ah! Yep. Well spotted. 

It's on the TODO now. 👍
