### ISSUE TITLE
An extra 'p' in y formula?

### ISSUE THREAD

**Issue by jonnross88** [koaning/calmcode-feedback#157]
There is an extra p in the plot which compares 2 probabilities. is that true or a typo?

![image](https://user-images.githubusercontent.com/68479485/159487281-5a2c6f8a-4860-4afd-8274-9aa5cb9c89c7.png)

![image](https://user-images.githubusercontent.com/68479485/159487398-b9a08d3c-07c8-4801-b16e-bbbf4cdad027.png)
 

Taken from https://calmcode.io/diseases/interact.html
It was taken from the 'extra' portion and you chose not to label the y-axis, so I am not sure if you were trying to show something else.

**Comment by koaning** [comment]
There indeed seems to be a y-axis missing, so that's fair to add. 

But the legend makes sense to me. You're comparing two probability lines, so it helps to distinguish.

**Comment by jonnross88** [comment]
I agree, the legend makes sense.
 The part which confused me was the 'p' outside the parentheses in g***p***(1-p)**g. 
Likewise for the '0.02'  in g*0.02*(1-0.02)**g. 
I was expecting g*(1-p)**g  and g*(1-0.02)**g respectively. Great content btw. I enjoy your teaching style and content.

**Comment by koaning** [comment]
Ah, now I see! Thanks for reporting. 

I'll need to manually check that, but it's added to the TODO :)

**Comment by koaning** [comment]
Fixed in an upcoming PR.
