### ISSUE TITLE
Yank - Unable to copy paste

### ISSUE THREAD

**Issue by advaitha** [koaning/calmcode-feedback#161]
https://calmcode.io/cool-cli/yank.html
I am using a linux system. I installed yank.
I copied text by hitting 'enter' at the text I wanted but I am not able to paste the copied text.
I tried ctrl+shift+v, p, shift+p - Nothing worked.
How to paste the text that was copied to the clipboard?

**Comment by koaning** [comment]
I am not the maintainer of the project, so it's hard for me to know for sure. Did you try consulting StackOverflow?

**Comment by koaning** [comment]
I'm closing this issue since my impression is that this issue is not related to a mistake on calmcode. I'll gladly hear it if the fix suggests otherwise.
