### ISSUE TITLE
Diseases series - mistake likely

### ISSUE THREAD

**Issue by mcaay** [koaning/calmcode-feedback#162]
Hey, in the series look at part 6 - "Updates". I have a mathematical issue with this solution and I think it's just not finished yet. What you calculated - optimal group sizes for a given probability - are only optimal **if we are allowed to only do one round of testing**. E.g. in your example you had 12 rounds/epochs. So if our goal would be to determine for every person if he is sick or not, we would need to add those test numers from all the rounds.

If you had a group size of 1, obviously that would be just 1 round of testing. If we had a group size of 2, we would need just 2 rounds of testing, therefore less rounds to sum up. Because of that, for p = 0.01 the optimal group size may be lower than 99 (I'm not sure). The optimization function would need to be expanded to sum over all the rounds to check it.

I guess it also depends on how exactly the goal is defined - in real life we might be tasked with finding the way to check everybody with the lowest number of tests or we can be told that we have only 3 months to do all the tests and this way logistics would also come into play.

My apologies that I can't spend more time to check it thoroughly right now, I just wanted to write it down quickly in case this is a problem.

**Comment by koaning** [comment]
It's certainly possible that there's an error in the video, but your description hasn't convinced me just yet. Could you pinpoint the flaw in my code and demonstrate a better alternative? 

> So if our goal would be to determine for every person if he is sick or not, we would need to add those test numers from all the rounds.

If a person has been proven to be healthy in a round before, we don't need to check them anymore. Once we start with a new group at the start of the epoch, I'm assuming that everybody has been shuffled. 

> in real life

This content describes a thought experiment that's not meant to perfectly resemble real life.

**Comment by koaning** [comment]
Closing due to radio silence.
