### ISSUE TITLE
Keep volume setting consistent after page reloads

### ISSUE THREAD

**Issue by nickdonnellyriis** [koaning/calmcode-feedback#165]
Currently, the volume setting resets to full volume every time a new page is loaded (or existing page reloaded). In my experience it is far too loud and I have to reset the volume to ~30% every time.

Nonetheless, keep up the great work fellas.

Browser: Latest Firefox
OS: Ubuntu 18.04

**Comment by koaning** [comment]
I don't know if it's possible to sync the player settings between pages, but it's worth a check. 

Not super high on the priority list, but worth a deeper dive for sure.
