### ISSUE TITLE
welcome

### ISSUE THREAD

**Issue by mortgoldman** [koaning/calmcode-feedback#167]
Challenge #2 , https://calmcode.io/challenge/helloworld.html, shows the word, WELCOME.  The answer only accepts "welcome" that is, in lower case.  I hate to sound critical.  Great work -- I really enjoy what you've put on the site.

--Mort

**Comment by koaning** [comment]
Ah yeah, that'd be a bug, thanks for reporting it. I thought I had a test for it, but I'll double-check later today.
