### ISSUE TITLE
404 at Calmcode blog

### ISSUE THREAD

**Issue by jonesmartins** [koaning/calmcode-feedback#173]
I found a bad URL at https://calmcode.io/blog/

![image](https://user-images.githubusercontent.com/15959626/194201634-6b527c88-d2e7-4173-80f9-f5a504b8b2a4.png)

The top URL is okay. The bottom URL is not.

**Comment by koaning** [comment]
Thanks for reporting, but this is a duplicate of https://github.com/koaning/calmcode-feedback/issues/171.
