### ISSUE TITLE
Navigating to typeguard.py from 'Search' tab results in 404 error

### ISSUE THREAD

**Issue by chiragpachori** [koaning/calmcode-feedback#180]
Don't forget to add a link (or a screenshot) of what needs a-fixin.

Looks like a simple case of page link pointing to a wrong location when accessed from search tab. Navigating from home page (under Shorts section) works fine.

### From Search tab:
1. Screenshot:
![image](https://user-images.githubusercontent.com/107985785/203642637-ba4d65d5-dabd-4a60-a1b0-67d39bf9e4d3.png)
2. Link:  https://calmcode.io/shorts/typeguard.html

### From Home page:
1. Screenshot:
![image](https://user-images.githubusercontent.com/107985785/203642971-a8f61db8-29fc-45a0-94ec-c4b5c59a9d54.png)
2. Link: https://calmcode.io/shorts/typeguard.py.html

**Comment by koaning** [comment]
The new site should fix this. Feel free to reopen if it appears again. New site should be live tonight!
