### ISSUE TITLE
Great Job:

### ISSUE THREAD

**Issue by abdul-raheem-shahzad** [koaning/calmcode-feedback#182]
Don't forget to add a link (or a screenshot) of what needs a-fixin.
Well I just wanted to appreciate the way you explained the lambda function in calmcode.io, I also loved your two hours long video on sklearn and sklego hats off to you great job and I am also making a playlist in Urdu language which will educate viewer about sklearn and skelgo especially, great job

**Comment by koaning** [comment]
Happy to hear it :) 

Just to check though; no issues on the website? If so, I will need to close the issue 😅.

**Comment by abdul-raheem-shahzad** [comment]
Dear Vincent D. Warmerdam,

I really enjoyed your videos on the topic that you covered in the two-hour
video. I recently made my own videos on the same topic, but in Urdu
language. I also explained the scikit lego in detail. I hope you will like
it. I am working here as an employee, Please check out my playlist.
https://www.youtube.com/watch?v=Rup8U2PmttM&list=PL9XvIvvVL50HZVnfJA2llCyKhqhQxm5Cn

Best regards,
Abdul Raheem Shahzad
Data Science and Machine Learning Instructor

**Comment by koaning** [comment]
Will close this issue due to spring cleaning.
