### ISSUE TITLE
"Must have skills" is plain silly link leads nowhere

### ISSUE THREAD

**Issue by oort77** [koaning/calmcode-feedback#186]
https://calmcode.io/labs/Must%20Have%20Skills[tm]%20is%20plain%20silly..html
<img width="826" alt="Screenshot 2023-02-13 at 15 52 33" src="https://user-images.githubusercontent.com/73858914/218476030-8e45089a-bd1c-45b9-acb1-373a828930e8.png">

**Comment by koaning** [comment]
Where did you find this link?

**Comment by oort77** [comment]
In the calmcode blog. But now it works fine))
