### ISSUE TITLE
Polars vs Pandas benchmark uses slow Pandas methods

### ISSUE THREAD

**Issue by dshemetov** [koaning/calmcode-feedback#188]
I think the Polars vs Pandas benchmark could use a different example. My feedback is in a comment on [the notebook gist here](https://gist.github.com/koaning/5a0f3f27164859c42da5f20148ef3856). I'm less interested in a Polars vs Pandas debate (I think [these benchmarks are pretty clear](https://h2oai.github.io/db-benchmark/)), I just want to educate people for best practices in both.

**Comment by koaning** [comment]
Ahhh good call. 

This certainly seems like a fair comment, one that is making me consider adding another video "episode" to the series. Pandas has been getting some tough love recently, and this certainly seems like an observation worth sharing. 

I do want to take the time to run this myself though. Something is making me wonder if the pandas 2.0 upgrade might improve things further.

**Comment by koaning** [comment]
I checked your code and left some feedback on the notebook.
