### ISSUE TITLE
Typo in polars tutorial 

### ISSUE THREAD

**Issue by fabridamicelli** [koaning/calmcode-feedback#189]
Fist things first: Thank you so much for putting together all these **awesome** learning resources :rocket:

Little error that I found:
The page `https://calmcode.io/polars/with_columns.html` has the typo `parallisation` which should read `parallelisation`, here's a screenshot:
![para](https://github.com/koaning/calmcode-feedback/assets/40115969/bf40d306-c24d-4b17-85e1-a7e59e772209)

Hope it helps.
Cheers
F

**Comment by koaning** [comment]
Thanks for reporting!
