### ISSUE TITLE
404 pur.py

### ISSUE THREAD

**Issue by dpprdan** [koaning/calmcode-feedback#191]
pur.py is found in the search
![grafik](https://github.com/koaning/calmcode-feedback/assets/1423562/3defe5d2-8252-4412-a94e-e339a26046f9)

But [the linked page](https://calmcode.io/shorts/pur.html) is a 404.

**Comment by koaning** [comment]
Thanks for the notification! Gotta add some more unit tests 😅.

**Comment by dpprdan** [comment]
Ha, I just went through the pytest courses 😁

I spotted a typo or two as well (don't remember where right now). Would you like them reported here as well or can I PR fixes somewhere?

**Comment by koaning** [comment]
Posting it here is fine. 

It's unclear if the project will allow for payments in the future, which is why it's kept closed source for now. If we ever end up responsible for user state, it's best to keep the code behind a wall.

**Comment by koaning** [comment]
Should be fixed now by the way!
