### ISSUE TITLE
typo pytest intro

### ISSUE THREAD

**Issue by dpprdan** [koaning/calmcode-feedback#192]
On https://calmcode.io/pytest/introduction.html  there is this sentence

> There's many libraries in python that will help with testing but a favourable on called [pytest](https://docs.pytest.org/en/latest/).

which ought to read (IMHO)

>  There are many libraries in python that will help with testing but a favourable one is [called] [pytest](https://docs.pytest.org/en/latest/).

"[called]" as in "could be omitted".

**Comment by koaning** [comment]
Just made the correction. Later this afternoon it should be fixed. 

Thanks for reporting!
