### ISSUE TITLE
Small typo on embeddings/results

### ISSUE THREAD

**Issue by schorfma** [koaning/calmcode-feedback#195]
Hello Vincent,

I noticed a small typo on <https://calmcode.io/embeddings/results.html>:

```diff
- [...]. After training is done, it looks liek this:
+ [...]. After training is done, it looks like this:
```

I really like the example and explanation you chose for the embeddings :+1: 
Thank you.

Greetings
Martin

**Comment by koaning** [comment]
Happy to hear it. Added the typo to the PR that adds a new course. Thanks!
