### ISSUE TITLE
calmcode/Embedding/Experiment compile missing

### ISSUE THREAD

**Issue by Dieter1955** [koaning/calmcode-feedback#196]
Hello Vincent, 

in the last code section model_pred is not defined. 
If you use model_emb then the compile is missing before fit.
-------------- original code ----------------
to_predict = OneHotEncoder(sparse=False).fit_transform(integers_out)
model_pred.fit(integers_in, to_predict, epochs=1, verbose=1)

preds = model_emb.predict(idx_to_calc)
-----------------------------------------------
Thanks Dieter

**Comment by koaning** [comment]
Good call. Made a change for the next public release. Thanks for reporting!
