### ISSUE TITLE
recursion: function (3rd video) Notes code issue

### ISSUE THREAD

**Issue by madalintat** [koaning/calmcode-feedback#198]
On the notes of the video the code is:

`def n_paths(start=1, end=5, jumps=(1, 2)):
    if start > end:
        return 0
    if start == end:
        return 1
    return npaths(start=start + 1, end=end) + npaths(start=start + 2, end=end)
`

You wrote npaths instead of n_paths :)

`def n_paths(start=1, end=5, jumps=(1, 2)):
    if start > end:
        return 0
    if start == end:
        return 1
    return n_paths(start=start + 1, end=end) + n_paths(start=start + 2, end=end)`
![Screenshot 2023-08-05 13 20 01](https://github.com/koaning/calmcode-feedback/assets/73785144/cf4f78e6-dad8-4a8c-9b06-79e3b17fabd4)

**Comment by koaning** [comment]
Well spotted. Will be taken into account the next time I push to main.
