### ISSUE TITLE
Easier bingewatching?

### ISSUE THREAD

**Issue by ondrejzacha** [koaning/calmcode-feedback#2]
Love the tutorials, super easy to understand and straight to the point!
One small thing I'd like to see would be a "Next video" button in a fixed position or some other way to "bingewatch" a single topic.

**Comment by koaning** [comment]
I wouldn't say that "bingewatching" is the best way to learn, but I've had this feature in my mind for a while. The next release should have this feature. 

Few quick questions about it though. 

1. Could you share a screenshot pointing out where you'd expect the button to be? 
2. Which content triggered you to check out the platform? 
3. I may be playing around with questions you can answer to check if you've understood a topic. Have you looked at the scikit-metrics content?

**Comment by ondrejzacha** [comment]
1. 
![image](https://user-images.githubusercontent.com/28254773/80208465-908e0480-8630-11ea-91df-d8de52236a98.png)
I'd say right side underneath the video is where I'd typically expect it, perhaps in a separate column so that the extra description isn't pushed further down.
2. I think I saw your Linkedin post and then checked a few courses from the first section. For me personally, it's a great way to check out tools that I have an idea about but haven't started using yet. I don't watch the videos necessarily to start using the tools right away but rather to get a quick overview of what are the pros/cons and how to get started. So I just check multiple topics at once, knowing that I can come back when I want to use them.
3. I checked it briefly now -- now I see that some of the sections _Score, Metrics, Refit, Charts, Score Settings, Flexibility_ seem to include the same or incorrect videos.
Imho for a more complex topic like scikit metrics it could be useful to have some extra questions, mostly because the crucial part is not so much about the tool but more about the underlying process. For the simpler topics I'd say it's not that necessary and could be even distracting (perhaps except for some short questions at the very end)

**Comment by koaning** [comment]
!? 

Interesting. You're the first person to notice. Putting it on the todo. Thanks :)

**Comment by koaning** [comment]
It should be fixed now. If you could let me know if scikit-metrics works with the video feature?

**Comment by ondrejzacha** [comment]
Yep, now it all looks correct!

**Comment by koaning** [comment]
Then I'll close this.
