### ISSUE TITLE
404 while manually editing the URL

### ISSUE THREAD

**Issue by falcaopetri** [koaning/calmcode-feedback#205]
I got a `404` trying to go from https://calmcode.io/course/context-managers/from-scratch to what I thought would be Context Managers' course homepage: https://calmcode.io/course/context-managers/.

I manually edited the first URL by removing the `/from-scratch` part, which is something that usually works on many sites using Clean URL or similar.

Of course, not all URL's path are required to mean something, but it might be a good addition on some cases to have an alias or redirection:
- https://calmcode.io/course/course-name -> https://calmcode.io/course/course-name/introduction *

Just for reference, these are other URLs I tried modifying:

|works|404|
|-----|---|
|https://calmcode.io/til/pandas-max-colwidth|https://calmcode.io/til|
|https://calmcode.io/course/context-managers/introduction|https://calmcode.io/course|

\* Some courses' introduction page seems to be named `/intro` (e.g., [virtualenv](https://calmcode.io/course/virtualenv/intro))

PS: The `Report 404.` button was a small but lovely detail!

**Comment by koaning** [comment]
This feels totally fair. Keeping this ticket around for later.

**Comment by koaning** [comment]
Just pushed a PR with a fix for this. Should be live in a few minutes.
