### ISSUE TITLE
500 when clicking on Next or Previous Video

### ISSUE THREAD

**Issue by GarrettMooney** [koaning/calmcode-feedback#206]
GIF shows the virtualenv section but the behavior seems global.

![Kapture 2024-02-04 at 20 11 30](https://github.com/koaning/calmcode-feedback/assets/4910020/b8ddd182-53af-4676-b96a-25deb3867e48)

**Comment by koaning** [comment]
Oh my. Yeah, for now you'll need the side buttons. Sorry about that!

**Comment by koaning** [comment]
Should be fixed. Thanks for reporting!
