### ISSUE TITLE
Button with broken links at human learn section

### ISSUE THREAD

**Issue by Johannes-Stephan** [koaning/calmcode-feedback#207]
The Links of the Previous and Next Buttons in the section of human learn are slightly incorrect.

The "Next Video" button on this Page: https://calmcode.io/course/human-learn/draw
refers to: "https://calmcode.io/course/human learn/missing" that is interpreted by the browser as "https://calmcode.io/course/human%20learn/missing" 
whereas the navigation on the right hand side of the video contains the correct link: "https://calmcode.io/course/human-learn/missing"

![image](https://github.com/koaning/calmcode-feedback/assets/149106916/b6952f62-c9a1-42b4-b197-d4018517652b)

**Comment by koaning** [comment]
Those are broken too? Mhm. It seems our transition to Django has broken a few things. 

Thanks for reporting though! Will have a look soon. 

> ps. This isn't Django's fault at all. But we did switch templating engines as a consequence.

**Comment by koaning** [comment]
I think I just fixed it in a PR. Will push in 5 minutes.
