### ISSUE TITLE
404 on tldraw short

### ISSUE THREAD

**Issue by timcolson** [koaning/calmcode-feedback#208]
Howdy folks - 
Love what ya do! Found ya via link from https://github.com/Textualize/toolong Great intro. :) 

Today, I stumbled onto the challenge. Fun! Did a few, and now I'm looking for info related to images.
 
https://calmcode.io/shorts/tldraw.com --> three SVGs are 404s. Doh! 
https://calmcode.io/shorts/imgs/tldraw-fancy-chart.svg -> 404

P.S. I also dig SVG and excalidraw.com, so I appreciate the intro to tldraw.com. Cool tool!

**Comment by koaning** [comment]
Ah yeah, we've switched our internal backends and this is totally "one of the many images" what haven't been automatically moved. Will add it to the TODO. Thanks for reporting!

**Comment by koaning** [comment]
Made the PR. Should be patched in 5 mins. Thanks for reporting!
