### ISSUE TITLE
pre-commit installation has a incorrect link

### ISSUE THREAD

**Issue by codeloop** [koaning/calmcode-feedback#21]
in the https://calmcode.io/pre-commit/installation.html, Pre-commit is linked to: https://github.com/google/gin-config, which imo should be linked to https://github.com/pre-commit/pre-commit, please check.
Below is the screenshot with the link underlined in red.
![image](https://user-images.githubusercontent.com/17523722/83967710-9b9bac00-a8e1-11ea-8634-a0a93c0ed466.png)

**Comment by koaning** [comment]
nice catch! will pick it up later tonight

**Comment by koaning** [comment]
Fixed it. It will now point to the official documentation page. Again, nice catch. Thanks!
