### ISSUE TITLE
Errors when installing scikit-learn 0.23.0 

### ISSUE THREAD

**Issue by daniszwarc** [koaning/calmcode-feedback#214]
Hello, I was trying to follow your video on scikit-learn [https://calmcode.io/course/scikit-learn/introduction](url) when I received this error during installation:

![2024-04-11_20-26-23](https://github.com/koaning/calmcode-feedback/assets/47301651/32ea2865-8b0e-4bcb-a787-fca8221891b4)
![2024-04-11_20-27-13](https://github.com/koaning/calmcode-feedback/assets/47301651/634cb7ba-ddd6-4edd-aeff-b3a8b5531d25)
I am not sure how to continue from here.
Thank you

**Comment by koaning** [comment]
I am unsure as well. I've never encountered an AIX system before. 

As an alternative, might a colab notebook suffice in the meantime? Installation issues can really depend on the laptop and something like colab should allow you to get going in the meantime.

**Comment by daniszwarc** [comment]
Hello Vincent and thank you for getting back to me.
I tried the same in Google Colab and got the same error:



I’ll try to follow another tutorial in the meanwhile.
Thanks again!

Thank you - Merci - Muchas gracias,

Dani Szwarc
***@***.***
ibmi.thiez.com

**Comment by koaning** [comment]
Closing since the issue seems specific.
