### ISSUE TITLE
dirty_cat has migrated to skrub. This package will no longer be maintained. Please use skrub instead.

### ISSUE THREAD

**Issue by mhd-habboub** [koaning/calmcode-feedback#219]
dirty_cat has migrated to [skrub](https://skrub-data.org/). This package will no longer be maintained. Please use [skrub](https://skrub-data.org/) instead.

**Comment by koaning** [comment]
Yeah, that course is due for a deprecation because of it. Will leave this issue open as a TODO for that.

**Comment by koaning** [comment]
Just pushed a small PR that fixes this.
