### ISSUE TITLE
Missing imports in Gazpacho episode notes

### ISSUE THREAD

**Issue by mccannjb** [koaning/calmcode-feedback#22]
The episode notes for the gazpacho series appear to be missing the "Soup" method import from gazpacho.
![Example](https://user-images.githubusercontent.com/2846154/83972235-f49d1d00-a8ac-11ea-96de-af0f10ee5e4d.png)

**Comment by koaning** [comment]
d0h. fixing right away. good call!

**Comment by koaning** [comment]
should be fixed. thanks!
