### ISSUE TITLE
example mini-project

### ISSUE THREAD

**Issue by kamil-kaczmarek** [koaning/calmcode-feedback#24]
Hey @koaning,

First of all thank you for making calmcode - I really like the videos and selection of tools presented :)

**The idea**
You present number of tools and show video-tutorials how to use them, starting from scratch. I think that it might be also valuable to show working example of few libs put together in some mini-project. Such project should be about some particular topic or solve some problem.

I have in mind one particular idea: *Generator of the images that looks like Piet Mondrian's abstract paintings.*

Example paintings: [one](https://commons.wikimedia.org/wiki/File:Piet_Mondriaan,_1921_-_Composition_en_rouge,_jaune,_bleu_et_noir.jpg) and [two](https://commons.wikimedia.org/wiki/File:Composition_A_by_Piet_Mondrian_Galleria_Nazionale_d%27Arte_Moderna_e_Contemporanea.jpg). Many more examples [here](https://commons.wikimedia.org/wiki/Category:Abstract_paintings_by_Piet_Mondrian).

**Why I think it's interesting?**
There are few arguments:
- Mondrian's art has some underlying mathematics, and there is [machine learning kernel](https://arxiv.org/pdf/1507.05181.pdf) inspired by this.
- You can visualize iterative process that creates an image (use gif)
- You can parameterize generative process in multiple different ways.

Please let me know what do you think about it?

Best,
Kamil

**Comment by koaning** [comment]
Hi Kamil, 

thanks for the feedback! I've been thinking about this theme of "combining topics" for a while. This is also why there's a few videos on datasets; the idea is to solve a practical problem and to show how I might go about it. Here's a list of things on my mind: 

- making a visualisation service using altair and fastapi 
- writing unit tests for pandas pipelines
- how to use cvxpy to write your own scikit-learn estimator 

I've found sofar that the dataset videos are the least popular though. And there's also still *so many* tools that really deserve attention. So a part of me likes the idea of making more of this "combining tools and solve a problem" but it's not high on the priority list.

I want to be little bit careful with generative art. I certainly agree that it is a wonderful topic but I think I'd prefer calmcode to stick to being a place where you can find "tools and thoughts that might make your professional life more enjoyable". I don't know if generative art is something that fits the professional life and there's a huge backlog of ai-fairness/pandas/scikit-learn related material that I think deserves priority at this phase.

If you know of any tricky datasets, possibly where fairness is an issue, I'd be all ears though.

**Comment by kamil-kaczmarek** [comment]
Hey @koaning,

Thanks for detailed explanation of your reasoning.

I agree, that generative art may not be optimal for featuring professional-oriented tools and problems.

Moving this idea to my personal "backlog" :)

I will, of course, let you know if I come across dataset that poses fairness challenges.
