### ISSUE TITLE
Slack threads?

### ISSUE THREAD

**Issue by gamesbook** [koaning/calmcode-feedback#27]
The picture you drew implied that Slack threads run inside of a channel, each in their own self-contained space and all publically available.

However this article from Verge (https://www.theverge.com/2017/1/18/14305528/slack-threads-threaded-messages) implies that the threads run parallel to (not "inside") a channel and are not publically available.

Perhaps you can create a short demo showing an actual worked environment inside of a Slack workspace.

**Comment by koaning** [comment]
You gotta help me here, which picture are you referring to? There's a lot of them on the calmcode website.

**Comment by gamesbook** [comment]
![slack](https://user-images.githubusercontent.com/354027/84631446-acee4500-aeed-11ea-8b73-eb8be43cc95d.png)

**Comment by koaning** [comment]
I'll keep this in mind. The article you share is a bit dated but I do agree that it may help to have a demo with slack shown to make it more tangible. 

It's on the TODO, don't know on what term I'll get to this but you make a fair suggestion here. :)

Thanks!
