### ISSUE TITLE
Pytest coverage comment

### ISSUE THREAD

**Issue by mpamey** [koaning/calmcode-feedback#28]
https://calmcode.io/pytest/coverage.html

pip install python-cov gives the following error: 'No matching distribution found for python-cov'.

Most people that have experienced this before will just add a version to the pip install. But for people that have not you could add a comment asking them to specify the version.

E.g.
Pip install pytest-cov==2.10.0

**Comment by koaning** [comment]
That's strange. When I run this command locally it works perfectly fine:

```
> python -m pip install pytest-cov
> python -m pip freeze | grep pytest
pytest==5.4.3
pytest-cov==2.10.0
```

Just to check, what operating system/python version are you running? This may be a python2 incompatibility.

**Comment by mpamey** [comment]
Windows, Python 3.8.1 
I made a new venv and after running your command it installed the packages without problems. 
`> python -m pip install pytest-cov`
pytest-5.4.3 pytest-cov-2.10.0

Not sure what the underlying problem was, but I can't even seem to reproduce it myself.
