### ISSUE TITLE
FastAPI Asnyc One

### ISSUE THREAD

**Issue by mrcartoonster** [koaning/calmcode-feedback#33]
In [Ansync One](https://calmcode.io/fastapi/async-one.html) you can remove the `r` variable. Flake 8 and the other Python linters go crazy about it saying `r` is declared but never used blah, blah, blah. Below is the re-write so the linters calm the freak down. 

```python
# -*- coding: utf-8 -*-
import asyncio
import time

from fastapi import FastAPI
from pydantic import BaseModel, validator

...

# Here's the re-write for the async portion
@app.get("/sleep_slow")
def sleep_slow():
    time.sleep(1)
    return {"status": "done"}


@app.get("/sleep_fast")
async def sleep_fast():
    await asyncio.sleep(1)
    return {"status": "done"}
```

**Comment by koaning** [comment]
Ahh well spotted! On the todo list. Thanks for reporting :)

**Comment by koaning** [comment]
Should be fixed after CI is done. Thanks for pinging and feel free to re-open if you see something went wrong.
