### ISSUE TITLE
Extra indentation

### ISSUE THREAD

**Issue by david26694** [koaning/calmcode-feedback#35]
I think there's an extra indentation in https://calmcode.io/pandas-pipe/calm.html. It's hard to spot though.

![image](https://user-images.githubusercontent.com/22721584/86381184-4f981900-bc8d-11ea-81ad-42859982f831.png)

**Comment by koaning** [comment]
Good catch. Fixed and should be patched in an hour. Feel free to re-open if it re-appears.
