### ISSUE TITLE
Docker overview 

### ISSUE THREAD

**Issue by prteek** [koaning/calmcode-feedback#38]
Hi ! Is it possible to have some kind of introduction to using docker in a less intimidating manner. I've been stuck at trying to understand it in the simplest form for me to be able to use it intuitively.

Thanks

**Comment by koaning** [comment]
What's the main thing that has blocked you sofar?

**Comment by prteek** [comment]
I am looking to deploy my dashboards as web apps and I found out docker is the way to do it. Although I don't quite find the concept simple to understand or use (my computer science skills are equivalent to an Amazonian Tribal), there are many tutorials that explain details of virtualisation etc. but I have no clue how to write a docker or Makefile.

**Comment by koaning** [comment]
Just to check; have you seen the video series on [Makefile](https://calmcode.io/makefiles/the-problem.html)? 

Docker certainly is on the list of things, but the list is *long*.

**Comment by prteek** [comment]
Thanks, I did not see it until now. :)

**Comment by prteek** [comment]
Awesome, that is very understandable. I'll be waiting for Docker then ;)
