### ISSUE TITLE
Missing parenthesis

### ISSUE THREAD

**Issue by david26694** [koaning/calmcode-feedback#40]
In https://calmcode.io/method-chains/keep.html, there's this piece of code:

`Clumper(poke_dict).keep(lambda d: 'Grass' in d['type']`

 I think it should be 

`Clumper(poke_dict).keep(lambda d: 'Grass' in d['type'])`

Very neat topic by the way :)

**Comment by koaning** [comment]
Glad to hear you like it! 

It's turning into an open source project next week and I'll be documenting the development.

**Comment by koaning** [comment]
I think I fixed the typo by the way. Feel free to reopen if it is not the case.
