### ISSUE TITLE
List constructor instead of comprehension

### ISSUE THREAD

**Issue by HrMaste** [koaning/calmcode-feedback#41]
Hello, great work on the whole calmcode.io.
I have a minor suggestion/question about https://calmcode.io/comprehensions/zip.html.
In the first part of the video shown here:

![list_comprehension](https://user-images.githubusercontent.com/17555419/89121687-37e8c600-d4c1-11ea-80fc-5700200f6abd.png)

Instead of using a list comprehension:
 `[(k,v) for k,v in d.items()]`

you could do:
`list(d.items())`

In my opinion it is more succinct and expressive, and also it is a bit faster on tests i did:
![time_comparison_calmcode](https://user-images.githubusercontent.com/17555419/89121807-8b0f4880-d4c2-11ea-8248-94dc240f927f.png)

**Comment by koaning** [comment]
The goal of the video is to show that you have access to both the keys/values at the same time in a comprehension. I'd also argue here that the example that is listed is more to help explain what is happening internally not to construct a list of tuples in the fastest way possible. 

I suppose I could add a sentence in the notes to make this point clear. But I would argue that `list(d.items())` is less expressive in the sense that you're less flexible in what you can do with the key/value combinations.

Perhaps the addition of this example makes the point more clear? 

```python
d = {'a':1, 'b':2}
double_dict = {k: v * 2 for k, v in d.items()}
```

**Comment by HrMaste** [comment]
If you need to edit the dictionary, I agree, explicit iteration is better.
