### ISSUE TITLE
Skill suggestion: Typer

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/calmcode-feedback#43]
I think it would be really nice to add a video about [click](https://click.palletsprojects.com/en/7.x/). If I can help with this somehow, let me know!

**Comment by koaning** [comment]
Thanks for bringing it up. It was already in my mind but there's two themes to that content. 

1. I want to wrap up Clumper and fairness mitigation techniques first. 
2. I'm wondering if [typer](https://typer.tiangolo.com/) > [click](https://click.palletsprojects.com/en/7.x/). I've used click all these years but there are some things about typer that I think are really nice. I don't know if it would be good to have both on the platform. But I've got some other content I'd want to make in the meantime.

**Comment by pim-hoeven** [comment]
I hadn't heard about typer before, looks really cool as well! And typer being the little brother of FastAPI is a good sign.

Definitely agree with you that it would be better to have one than both. Some thoughts
- Benefit of doing click would be that it has been used a lot more and is more common in already existing codebases . On the other hand, Flask was / is also used a lot more than FastAPI, but I like FastAPI waaaaay better.
- I like the typer syntax in 'simple' cases, but I think click is cleaner in more complicated cases: typer can make arguments very large.

This is just based on scanning the typed documentation though, so very curious to learn what your take on typer is!

**Comment by koaning** [comment]
I've got a similar experience. The extra stuff with large arguments is kind of what you get if you want to take types serious. I don't see a way around that. I've used click and I still love it. But I prefer to only have one CLI tool on this platform.

**Comment by koaning** [comment]
I have decided that it's going to be `Typer`

**Comment by koaning** [comment]
Aaaaaand I've finally made the videos. They are q'd up for next release.
