### ISSUE TITLE
Skill suggestion: Logging

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/calmcode-feedback#45]
So as you might have noticed: I'm using calmcode as a means to explain some concepts to someone in my team. Everytime a new concept comes up, I think: let's see if there's a nice video about this. The topic of today was 'Logging'

Might be very cool to have a video about this. Some subtopics might include:
- Benefits of logging vs print
- Write to files and stdout
- Define formatting
- The awesome `log_pd` decorator in `sklego`

Let me know if I can be of any help

**Comment by koaning** [comment]
Not to forget the [rich handler](https://github.com/willmcgugan/rich#logging-handler). 

I might just get started with this today. 

Out of curiosity ... do your colleagues have any feedback?

**Comment by pim-hoeven** [comment]
Awesome!

And that rich handler! This is the coolest thing, completely missed it. Gonna start changing my loggers right away 😄

**Comment by koaning** [comment]
The pandas logging will be handled later because there's some PRs happening there soon-ish. I might push some of this tonight. Might be later though. Just got paper mario on Nintendo Switch ... so ...

**Comment by pim-hoeven** [comment]
Nice! Thanks @koaning!!
