### ISSUE TITLE
Some spelling mistakes, missing quotations and such

### ISSUE THREAD

**Issue by Pverheijen** [koaning/calmcode-feedback#47]
https://calmcode.io/pre-commit/how-it-works.html
need to edit the video, last sentences get repeated twice (with different endings)

https://calmcode.io/gin/intro-to-gin.html
def simulate(n_samples) 
missing : at end of function declaration

if __name__ = __main__:
forgot to put __main__ in quotation marks in the code example below

config.gin not within quotation marks

same for https://calmcode.io/gin/required-settings.html

https://calmcode.io/gin/blacklist.html
code example has no default value for argument n_samples
def simulate(random_func, n_samples):

@gin.configurable(blacklist=[n_samples])
n_samples not in quotation marks
neither is __main__

same remarks for
https://calmcode.io/gin/external-configurations.html

**Comment by koaning** [comment]
I added a colon to `def simulate` in https://calmcode.io/gin/intro-to-gin.html. 

I cannot find the quotation bug for main. 

I cannot find the quotation bug for `config.gin` either. 

I also feel like there are definately quotes around `n_samples` here: https://calmcode.io/gin/blacklist.html. 

Just to check. On what device are you watching this? I haven't checked the videos yet but your code suggestions don't seem to align with the website. If you could check again, could you then also list the link and what is wrong with it in the comments below? That makes it easier for me to tick off.

**Comment by koaning** [comment]
As for video editing. 

- [x] 00:38 https://calmcode.io/gin/intro-to-gin.html
- [x] 03:30 https://calmcode.io/pre-commit/how-it-works.html

**Comment by koaning** [comment]
Everything seems fixed and updated on my end. Feel free to re-open if you disagree.
