### ISSUE TITLE
changes to mkdocs.yml in calmcode, mkdocs, MaterialMkdocs

### ISSUE THREAD

**Issue by mattoppenheim** [koaning/calmcode-feedback#49]
https://calmcode.io/mkdocs/material-mkdocs.html

  logo: 
    icon: cloud

now needs to be:

    icon:
        logo: material/cloud

or this error is generated:

mkdocs AttributeError: 'dict' object has no attribute 'split'

Thanks for the series.

**Comment by koaning** [comment]
Working on the update now. Should be live on the site in about 10 minutes.
