### ISSUE TITLE
Small corrections to text in calmcode.io/story and /faq

### ISSUE THREAD

**Issue by capar** [koaning/calmcode-feedback#51]
Corrections:

https://calmcode.io/story.html

lof --> lot

https://calmcode.io/faq.html

tech tech together --> teach (teaching?) tech together  (they seem to call themselves _teaching_ tech together at https://github.com/gvwilson/teachtogether.tech )

what data we collection --> we collect

is a surprisingly buggy --> is surprisingly buggy

definately --> definitely

An better experience --> A better experience

to-do list vs todo list (two different spellings in two places)

Thank you!

**Comment by koaning** [comment]
Making the corrections now. Thanks! The changes should be live in about 10 minutes.

**Comment by capar** [comment]
Thank you!
