### ISSUE TITLE
entr install

### ISSUE THREAD

**Issue by mrcartoonster** [koaning/calmcode-feedback#52]
Don't forget to add a link (or a screenshot) of what needs a-fixin.
[entr](https://calmcode.io/entr/introduction.html)
I have a MacBook and the `entr` command wasn't installed by default. I did a quick homebrew search and installed it. If you can add to the Notes section on how to install it quickly. Thank you for the introduction to this cool little command. Will be using it in my workflow. 😃

**Comment by koaning** [comment]
Just to check, isn't the install command listed on the 2nd video? Or was the issue that you did not have brew?

**Comment by koaning** [comment]
Looking [here](https://calmcode.io/entr/entr.html) I do seem to see the brew install command.

**Comment by mrcartoonster** [comment]
I see it. Ooops. Thanks
