### ISSUE TITLE
There is no bold syntax in the output on Pycharm

### ISSUE THREAD

**Issue by utkuozsan** [koaning/calmcode-feedback#54]
from rich.console import Console
from rich.theme import Theme

custom_theme = Theme({
    "good" : "green",
    "bad": "bold red"
})

console = Console(theme=custom_theme)
console.print("File downloaded!", style="good")
console.print("File corrupted!", style="bad")
console.print("The internet is [bad]down![/bad]")

![image](https://user-images.githubusercontent.com/3276112/93006804-8336cf80-f569-11ea-998e-2f406e966aa0.png)

**Comment by koaning** [comment]
If the shell that you're using does not support making text bold then rich won't be able to add it. This is similar to colors. Not every shell allows you to add color to the output. If this was unclear then we might add it as a footnote to a video but if you'd like to explore this in more detail it might be better instead mention this over on the rich repository.
