### ISSUE TITLE
How to specify the .flake8 file in a pre-commit?

### ISSUE THREAD

**Issue by jroberayalas** [koaning/calmcode-feedback#55]
I got a question regarding this [video](https://calmcode.io/test/pre-commit.html) that is part of the test series: how can you specify the .flake8 file to be run within the flake8 pre-commit?

**Comment by koaning** [comment]
I think it should pick it up automatically assuming the `.flake8` file is in the root of the project. Just to check, this isn't working on your side?

**Comment by jroberayalas** [comment]
Yes, I move the `.flake8` file to the root of the project and it works. Apologies for this.

**Comment by koaning** [comment]
@jroberayalas no need to apologize! If this wasn't clear from the document, then I prefer to keep the issue open as a reminder. I should make it explicitly clear that the file needs to be in the root of the project.

**Comment by koaning** [comment]
Closing due to radio silence.
