### ISSUE TITLE
Use chapters instead of seperate videos

### ISSUE THREAD

**Issue by iewaij** [koaning/calmcode-feedback#59]
First of all, I'm extremely grateful for the awesome content you have made that put all the tutorials together. It's like a lite version of [the missing semester](https://missing.csail.mit.edu/). I do have a slight suggestion though. The videos for each topics are separated into different pages. This makes it difficult to see the whole content and jumping through different parts. [Chapter is now available for vimeo](https://vimeo.com/blog/post/easy-navigation-for-your-videos-with-chapters/) and it would be great if this feature is used.

**Comment by koaning** [comment]
It's going to be *a lot* of work to convert everything into chapters but I agree that there's a downside to the pages. They make some sense, but I wonder if there's a nice way to perhaps put it all into a single page.

Will leave this issue open so folks can contribute to the design topic.

**Comment by koaning** [comment]
There's a redesign on the way that should address this. 

![image](https://user-images.githubusercontent.com/1019791/111081514-f9f65a80-8503-11eb-97e3-7eea17b6125e.png)

It's still sep pages. But at least now it'll be clearer that they are connected.
