### ISSUE TITLE
Missing notebook for dirty-cat

### ISSUE THREAD

**Issue by Daandamhuis** [koaning/calmcode-feedback#62]
Don't forget to add a link (or a screenshot) of what needs a-fixin.
The link that is in the [last part](https://calmcode.io/dirty-cat/results.html) of the video links to; https://calmcode.io/notebooks/dirty-cat.ipynb but this isn't correct.

**Comment by koaning** [comment]
"Le Strange!" 

I'll have a look right away.

**Comment by koaning** [comment]
The CI is triggered for a fix. Gitlab has a big queue it seems, but it's in the works. Will close once I confirm it's live.
