### ISSUE TITLE
recursion: function video 3

### ISSUE THREAD

**Issue by cmougan** [koaning/calmcode-feedback#63]
In the Notes, the function corresponds to the one of later video 5

def n_paths(start=1, end=5, jumps=(1, 2)):
    if start > end:
        return 0
    if start == end:
        return 1
    return sum([n_paths(start=start + j, end=end) for j in jumps])

and not the one of this correspondent video (https://calmcode.io/recursion/function.html) video 3

<img width="854" alt="Screenshot 2020-12-10 at 07 34 04" src="https://user-images.githubusercontent.com/43068386/101730325-1e343c80-3aba-11eb-90be-36184e202ec9.png">

**Comment by koaning** [comment]
Added it to a PR for a fix. Thanks for reporting!
