### ISSUE TITLE
Typo in gazpacho video 2 notes

### ISSUE THREAD

**Issue by lucasmelin** [koaning/calmcode-feedback#68]
Typo in the notes here: https://calmcode.io/gazpacho/get.html

In the line 

> To use gazpacho to download the website you'll need to run the folling code;

**folling** should instead be **following**.

**Comment by koaning** [comment]
Strange. When I check live it seems to be correct. 

![image](https://user-images.githubusercontent.com/1019791/104090513-9045a000-5277-11eb-9287-18be06d327bd.png)

Will close the issue now. Feel free to re-open if it persists tho.
