### ISSUE TITLE
tqdm vs. Rich?

### ISSUE THREAD

**Issue by morberg** [koaning/calmcode-feedback#74]
I don’t understand what tqdm gives me that is not available when using [rich to display progress](https://rich.readthedocs.io/en/stable/progress.html).

I understand you are looking at describing Typer which has a third way to display progress. Explaining when to use what would be useful. Thanks.

**Comment by koaning** [comment]
Notice the level of freedom given here;

```
progress.update(task, advance=0.5)
```

1. You can call the update when you like, it doesn't require an update on every iteration of an iterable. 
2. You can determine how much progress is advanced, the amount of "update" can also be something else than '+1' 
3. Rich gives you more control over layout, colors and style. 

The downside is that it's likely to be slower. 

Just to check, does the content on `calmcode` discuss the progress bars from rich? Your question suggests it does but I can't find it on the website.

**Comment by morberg** [comment]
I started using rich thanks to calmcode, not sure if it covers progress bars. 

One thing I find difficult is choosing the right package when there are many choices. It would be nice if calmcode could be opinionated and say ‘for use case x, use package y’.

I know the current structure on calmcode is focused on packages, but as a programmer I want to achieve something. What package I use is less important.  If anything, the fewer packages I need to learn the better.

**Comment by koaning** [comment]
I see what you're saying there but I think there's a limit to what calmcode can do in terms of advice along the lines of "for use case x, use package y". The thing is; there are **so many** use cases out there. Many of them are so specific that it is very hard for me to give general advice upfront. The packages that are presented on the site are all useful, but probably not to everyone all the time.
