### ISSUE TITLE
Ray articles have a description from older altair articles in the header

### ISSUE THREAD

**Issue by kbaikov** [koaning/calmcode-feedback#75]
See the screenshot attached.
![image](https://user-images.githubusercontent.com/4488943/106369006-56375d80-634e-11eb-9abf-6c1effc05b10.png)

**Comment by koaning** [comment]
Ah. Good catch. It shouldn't list altair there. Thanks!

**Comment by koaning** [comment]
Fixed. https://calmcode.io/ray/introduction.html

Thanks for reporting!
