### ISSUE TITLE
Transcribing the videos and including in Notes

### ISSUE THREAD

**Issue by oagbaneje** [koaning/calmcode-feedback#76]
Just stumbled on your awesome website. Really love the conciseness if the videos. I was wondering if a transcript could be added to the **Notes** section or a separate tab. I didn't see an option for subtitles in the video either. I would be happy to help with transcribing.

**Comment by koaning** [comment]
Transcribing is *a lot* of work. But it's something I'll keep in mind. If I do transcribing I prefer to immediately do all the content though. Might prefer to do that with an organisation than through voltuneers due to all the review work involved.

**Comment by oagbaneje** [comment]
Thanks for considering it! I think getting an organization to do transcribe the videos is a good idea.

**Comment by koaning** [comment]
I'm mentioning here that I'm open to suggestions on how to perhaps automate this. The videos are hosted on vimeo but the transcripts would also help folks find the videos. SEO and stuff doesn't look in the video but it will pick up on words that are listed as transcripts.

**Comment by koaning** [comment]
I am considering [rev](https://www.rev.com/blog/resources/how-to-transcribe-a-vimeo-video-to-text).

**Comment by koaning** [comment]
The more I've been thinking about it the more that I think the transcripts are too much of a "nice to have". I'd rather have better Appendices such that folks who don't watch the video can enjoy the content. Will close the ticket for now.
