### ISSUE TITLE
Ray Speedup Clarification

### ISSUE THREAD

**Issue by koaning** [koaning/calmcode-feedback#77]
This is a fair point. https://twitter.com/Co_Martel/status/1356528594634342401

**Comment by ceteri** [comment]
@koaning, if you'd like more extended examples of using the Ray core as design patterns for parallelizing Python codes, here's a tutorial developed for Ray+Anyscale: https://github.com/DerwenAI/ray_tutorial

There's some work on profiling, to help decide where to make trade-offs – see the `pi.ipynb` examples.

We'll use these examples plus the slides as the basis for a tutorial at Ray Summit, although they're open and shared.

**Comment by koaning** [comment]
@ceteri Thanks for sharing!

I'll keep it on my ... ray-dar. 😉

**Comment by ceteri** [comment]
![image](https://user-images.githubusercontent.com/57973/114255072-f1a90800-9967-11eb-89a1-8a844afd045f.png)
