### ISSUE TITLE
 scikit metrics: Part - Metrics

### ISSUE THREAD

**Issue by Daandamhuis** [koaning/calmcode-feedback#8]
Hi! 

First of all, thanks for the great content! 

So I was looking at your videos of scikit metrics and I noticed that the video in the [Metric](https://calmcode.io/scikit-metrics/metrics.html) seems like the full screen recording with some overlap into the Refit Part.
- "Blank screen" in video from 1:45 untill 2:09.
- Around 2:09 you are talking about the scoring which also happens in the video of [Refit](https://calmcode.io/scikit-metrics/refit.html)

**Metrics**
![image](https://user-images.githubusercontent.com/3600611/80948404-4ce68800-8df2-11ea-9749-a579b0c52148.png)

**Refit**
![image](https://user-images.githubusercontent.com/3600611/80948460-6e477400-8df2-11ea-9b0f-794435d67abc.png)

**Comment by koaning** [comment]
Yeah that really sounds like a mistake on my part. When I've got the time, I'll re-render. Thanks for bringing it up!

**Comment by koaning** [comment]
Ah yeah, found the bug. Really weird. Am rendering anew right now.

**Comment by Daandamhuis** [comment]
Haha good to know! You’ve created really helpful content, so I thought I’d return a small contribution 😄

**Comment by koaning** [comment]
This should now be fixed. Feel free to re-open if you spot the same issue back.
