### ISSUE TITLE
Notebook not found : Broken Link

### ISSUE THREAD

**Issue by 123nishant** [koaning/calmcode-feedback#81]
Hi Team ,

I wasn't able to find out the notebook for this page. 

https://calmcode.io/dirty-cat/results.html

Can you please chekc it out ? 

![image](https://user-images.githubusercontent.com/8594023/110283517-3ad30880-8006-11eb-86c9-89d2df60ae5d.png)

**Comment by koaning** [comment]
Thanks for reporting! I've found the dead link. This should be fixed within 15 mins (it's rendering the new website right now).

**Comment by koaning** [comment]
Mhmm ... still persists. Opening up again.

**Comment by koaning** [comment]
Just pushed another attempt.
