### ISSUE TITLE
Return statement of fetch.py is not spelt correctly

### ISSUE THREAD

**Issue by ejmurray** [koaning/calmcode-feedback#82]
Update the spelling of the return statement for **fetch.py** for the second videos code example near the bottom of the page.

**Comment by koaning** [comment]
Two observations. 

1. It is *really* hard for me to know which page you're referring to. The website currently hosts 400+ video pages so without a link to the page I won't be able to make a quick fix. 
2. spelt -> spelled ;)

**Comment by ejmurray** [comment]
Sorry. The error is on the following page:

https://calmcode.io/logging/format.html

The final return statement for the last bit of code.

**Comment by koaning** [comment]
Fixed for the next release. Thanks for reporting.
