### ISSUE TITLE
Missing line of code in 2nd example

### ISSUE THREAD

**Issue by schorndorfer** [koaning/calmcode-feedback#84]
from rich.console import Console

console = Console()

console.print("This is some text.")
console.print("This is some text.", style="bold")
console.print("This is some text.", style="bold underline")
console.print("This is some text.", style="bold underline red")
console.print("This is some text.", style="bold underline red on black")

**Comment by koaning** [comment]
d0h! well spotted.

it's on the PR for the next release. thanks for reporting!
