### ISSUE TITLE
Broken link on https://calmcode.io/datasette/authenticate.html

### ISSUE THREAD

**Issue by kynan** [koaning/calmcode-feedback#85]
> Adding a password will also require programmatic access to provide credentials. An easy way to explore this is to use [insomnia](https://insomnia.rest/). If you're unfamiliar with it, you might appreciate our [tutorial](https://calmcode.io/mac-apps/rest-ui.html).

The tutorial link is a 404.

**Comment by koaning** [comment]
d0h! 

This is the correct link: https://calmcode.io/mac-apps/insomnia.html. Added on the todo to fix in the next release. 

Thanks for reporting!

**Comment by koaning** [comment]
This should be fixed in next week's release. Again, thanks for reporting!
