### ISSUE TITLE
Contents description for Game of Thrones dataset is incorrect

### ISSUE THREAD

**Issue by Hugovdberg** [koaning/calmcode-feedback#90]
A friendly reminder as per this tweet: https://twitter.com/hugovandenberg/status/1381291234937999362

On https://calmcode.io/datasets/got.html the schema description of the Game of Thrones dataset is wrong. I'm not sure what the correct descriptions are, but last time I checked there were no pokemon in GoT.

**Comment by koaning** [comment]
There's a PR ready with a fix. Should be out this friday/saturday after I fix the merge bugs :)

**Comment by koaning** [comment]
Fixed! https://calmcode.io/datasets/got.html
