### ISSUE TITLE
Method(s) differ from what is shown in video

### ISSUE THREAD

**Issue by jamestexas** [koaning/calmcode-feedback#91]
Don't forget to add a link (or a screenshot) of what needs a-fixin.

On [pt. 3 (behaviors) of "Decorators"](https://calmcode.io/decorators/behavior.html) the code below is as follows.  The difference is that the "sleep_random()" method does not take an argument in the video, but does in the code sample. 

```
import time
import random

def stopwatch(f):
    def func():
        tic = time.time()
        result = f()
        print(f"this function took: {time.time() - tic}")
        return result
    return func

def sleep_random(s):
    t = s + random.random()
    time.sleep(t)
    return "Done!"

timed_sleep = stopwatch(sleep_random)
```

The code shown in the video is as follows:
```
import time
import random

def stopwatch(f):
    def func():
        tic = time.time()
        result = f()
        print(f"this function took: {time.time() - tic}")
        return result
    return func

def sleep_random():
    time.sleep(random.random())
    return "Done!"

timed_sleep = stopwatch(sleep_random)
```
![image](https://user-images.githubusercontent.com/18285880/114756022-ebc47580-9d1f-11eb-8408-64c412e755f0.png)

**Comment by koaning** [comment]
Good catch. It's likely this was a copy/paste bug on my end. Will patch a fix right away.

**Comment by koaning** [comment]
Fixed https://calmcode.io/decorators/behavior.html.
