### ISSUE TITLE
https://calmcode.io/human-learn/missing.html - minor correction on code snippet

### ISSUE THREAD

**Issue by AravindNambiar** [koaning/calmcode-feedback#93]
old_example = pd.DataFrame([{
    'island': 'Torgersen',
    'bill_length_mm': 39.1, #actual value in video instead of nan
    'bill_depth_mm': 18.7,
    'flipper_length_mm': 220.0,
    'body_mass_g': 5750.0,
    'sex': 'male'}
])

new_example = pd.DataFrame([{
    'island': 'Torgersen',
    'bill_length_mm': np.nan,
    'bill_depth_mm': 18.7,
    'flipper_length_mm': 220.0,
    'body_mass_g': 5750.0,
    'sex': 'male'}
])

model.predict_proba(old_example)
model.predict_proba(new_example)

**Comment by koaning** [comment]
I just merged a PR with this fix. Thanks for reporting 👍
