### ISSUE TITLE
Gazpacho depracted Soup.find strict parameter

### ISSUE THREAD

**Issue by mrcartoonster** [koaning/calmcode-feedback#95]
Don't forget to add a link (or a screenshot) of what needs a-fixin. If you can update the code in [Gazpacho: Strict](https://calmcode.io/gazpacho/strict.html) to reflect that `Soup.find` strict parameter has been deprecated and now the correct parameter is [partial](https://gazpacho.xyz/#partial).

**Comment by koaning** [comment]
Good point, added this to the to-do list!

**Comment by koaning** [comment]
The merge request for the new videos/code is in the pipeline right now. Thanks again for reporting!
