### ISSUE TITLE
Add reference to logging for pandas.pipe content

### ISSUE THREAD

**Issue by Hugovdberg** [koaning/calmcode-feedback#98]
As you are using [this tutorial](https://calmcode.io/pandas-pipe/logs.html) to make people aware that
- style matters 
- good style makes it easier to transition to production code
- dropping the logging decorator without much explanation of the details
- the stdlib logging module prints to stdout if no logfile is configured

I would suggest using `logging.info` instead of `print` and refer to your logging tutorial. Most users wouldn't note much difference, but it makes the code even nicer when bringing it to production. 

If editing the videos is too much work then perhaps a reference in the notes wood go a long way to spike people's interest.

**Comment by koaning** [comment]
If you go to the implementation that we [open-sourced in scikit-lego ](https://scikit-lego.netlify.app/pandas_pipeline.html) you'll find that we actually use logging. But there's a very conscious reason not to add it to this tutorial. 

The tutorial is meant for folks who are using pandas in a notebook. Odds are that the person watching this is a college student who is just learning about pandas. That means that logging might be an entirely new concept. To keep the mental overhead small it's better to only explain one concept at a time.

That said, it is a fair comment to add in the appendix. I'm also seeing that the scikit-lego feature isn't listed.

**Comment by koaning** [comment]
Just pushed a PR with a fix.
